"""
Workflow Verification Script — tests all 5 documented workflows end-to-end.
Run with: uv run python workspace/verify_workflows.py
"""

import asyncio
import importlib
import json
import os
import sys
from pathlib import Path

# ── Bootstrap: point at our venv and load .env ──────────────────────────────
repo_root = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(repo_root))

from dotenv import load_dotenv
load_dotenv(repo_root / ".env")

# ── Colours ─────────────────────────────────────────────────────────────────
GREEN  = "\033[92m"
RED    = "\033[91m"
YELLOW = "\033[93m"
CYAN   = "\033[96m"
BOLD   = "\033[1m"
RESET  = "\033[0m"

results = []

def ok(label, detail=""):
    results.append(("PASS", label))
    print(f"  {GREEN}✓ PASS{RESET}  {label}" + (f" — {detail}" if detail else ""))

def fail(label, detail=""):
    results.append(("FAIL", label))
    print(f"  {RED}✗ FAIL{RESET}  {label}" + (f" — {detail}" if detail else ""))

def warn(label, detail=""):
    results.append(("WARN", label))
    print(f"  {YELLOW}⚠ WARN{RESET}  {label}" + (f" — {detail}" if detail else ""))

def section(title):
    print(f"\n{BOLD}{CYAN}══ {title} ══{RESET}")


# ── Workflow 1: Morning Briefing ─────────────────────────────────────────────
async def workflow_1():
    section("Workflow 1: Morning Briefing")
    from server import mcp

    # get_current_time
    try:
        result = await mcp.call_tool("get_current_time", {})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "ISO 8601" in text:
            ok("get_current_time", text[:60])
        else:
            fail("get_current_time", text[:80])
    except Exception as e:
        fail("get_current_time", str(e))

    # get_world_news
    try:
        result = await mcp.call_tool("get_world_news", {})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "BRIEFING" in text.upper() or len(text) > 100:
            ok("get_world_news", f"{len(text)} chars returned")
        else:
            warn("get_world_news", "Short/empty response — may be network issue")
    except Exception as e:
        warn("get_world_news", str(e))

    # get_context_stats (context_manager)
    try:
        result = await mcp.call_tool("get_context_stats", {})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Turns" in text or "turns" in text.lower():
            ok("get_context_stats", text.split("\n")[1] if "\n" in text else text[:60])
        else:
            fail("get_context_stats", text[:80])
    except Exception as e:
        fail("get_context_stats", str(e))

    # get_session_summary
    try:
        result = await mcp.call_tool("get_session_summary", {})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        ok("get_session_summary", f"{len(text)} chars")
    except Exception as e:
        fail("get_session_summary", str(e))


# ── Workflow 2: Deep Research + Report ───────────────────────────────────────
async def workflow_2():
    section("Workflow 2: Deep Research + Report Generation")
    from server import mcp

    # search_web (tests cache too)
    try:
        result = await mcp.call_tool("search_web", {"query": "agentic AI frameworks 2025"})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Search results" in text or len(text) > 100:
            ok("search_web", f"{len(text)} chars — first call (cache MISS expected)")
        else:
            warn("search_web", text[:80])
    except Exception as e:
        warn("search_web", str(e))

    # search_web again (should be cache HIT)
    try:
        result = await mcp.call_tool("search_web", {"query": "agentic AI frameworks 2025"})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if len(text) > 100:
            ok("search_web [cache HIT]", "Repeated call returned instantly")
        else:
            warn("search_web [cache HIT]", text[:80])
    except Exception as e:
        warn("search_web [cache HIT]", str(e))

    # create_document
    try:
        result = await mcp.call_tool("create_document", {
            "filename": "research_test.md",
            "content": "# Agentic AI Research\nTest report generated by workflow verification."
        })
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "research_test.md" in text:
            ok("create_document", text[:80])
        else:
            fail("create_document", text[:80])
    except Exception as e:
        fail("create_document", str(e))

    # get_file_contents to verify
    try:
        result = await mcp.call_tool("get_file_contents", {"file_path": "research_test.md"})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Agentic AI Research" in text:
            ok("get_file_contents [verify]", "File content confirmed")
        else:
            fail("get_file_contents [verify]", text[:80])
    except Exception as e:
        fail("get_file_contents [verify]", str(e))


# ── Workflow 3: Desktop Automation ───────────────────────────────────────────
async def workflow_3():
    section("Workflow 3: Desktop Automation (Permission-Aware)")
    from server import mcp

    # run_permission_diagnostics
    try:
        result = await mcp.call_tool("run_permission_diagnostics", {})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Screen Recording" in text and "Accessibility" in text:
            ok("run_permission_diagnostics", "Report generated")
            # Print abbreviated permission status
            for line in text.splitlines():
                if "###" in line:
                    print(f"         {line.strip()}")
        else:
            fail("run_permission_diagnostics", text[:80])
    except Exception as e:
        fail("run_permission_diagnostics", str(e))

    # get_running_apps (tests graceful permission handling)
    try:
        result = await mcp.call_tool("get_running_apps", {})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Running apps" in text or "Permission Denied" in text:
            ok("get_running_apps", text.split("\n")[0])
        else:
            warn("get_running_apps", text[:80])
    except Exception as e:
        fail("get_running_apps", str(e))

    # list_open_windows (tests graceful permission handling)
    try:
        result = await mcp.call_tool("list_open_windows", {"limit": 5})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Open windows" in text or "Permission Denied" in text:
            ok("list_open_windows", text.split("\n")[0])
        else:
            warn("list_open_windows", text[:80])
    except Exception as e:
        fail("list_open_windows", str(e))

    # inspect_desktop_screen — WARN expected (no screen recording)
    try:
        result = await mcp.call_tool("inspect_desktop_screen", {"question": "What is visible?"})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Screen recording permission" in text or "Desktop screenshot" in text:
            warn("inspect_desktop_screen", "Permission missing — graceful error confirmed ✓")
        else:
            ok("inspect_desktop_screen", text[:60])
    except Exception as e:
        fail("inspect_desktop_screen", str(e))


# ── Workflow 4: Git Workflow ──────────────────────────────────────────────────
async def workflow_4():
    section("Workflow 4: Git Workflow (Read-Only)")
    from server import mcp

    # git_status
    try:
        result = await mcp.call_tool("git_status", {"repo_path": str(repo_root)})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Git Status" in text or "branch" in text.lower():
            ok("git_status", text.split("\n")[0])
        else:
            fail("git_status", text[:80])
    except Exception as e:
        fail("git_status", str(e))

    # git_branch
    try:
        result = await mcp.call_tool("git_branch", {"repo_path": str(repo_root)})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Branches" in text or "main" in text:
            ok("git_branch", text.strip().replace("\n", " | ")[:80])
        else:
            fail("git_branch", text[:80])
    except Exception as e:
        fail("git_branch", str(e))

    # git_log
    try:
        result = await mcp.call_tool("git_log", {"repo_path": str(repo_root), "limit": 3})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if len(text) > 20:
            ok("git_log", f"{len(text.splitlines())} lines returned")
        else:
            warn("git_log", text[:80])
    except Exception as e:
        fail("git_log", str(e))

    # git_diff (read-only — safe)
    try:
        result = await mcp.call_tool("git_diff", {"repo_path": str(repo_root)})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        ok("git_diff", f"{len(text)} chars of diff output")
    except Exception as e:
        warn("git_diff", str(e))

    # store_action_trace (simulate logging a git push)
    try:
        result = await mcp.call_tool("store_action_trace", {
            "goal": "git push verification",
            "outcome": "Workflow 4 verified successfully",
            "tool_events": [{"name": "git_status", "ok": True}, {"name": "git_branch", "ok": True}],
            "status": "completed"
        })
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "stored" in text.lower():
            ok("store_action_trace", text)
        else:
            fail("store_action_trace", text[:80])
    except Exception as e:
        fail("store_action_trace", str(e))


# ── Workflow 5: Session Management ───────────────────────────────────────────
async def workflow_5():
    section("Workflow 5: Session Management")
    from server import mcp

    # Save a session note
    try:
        result = await mcp.call_tool("save_session_note", {
            "note": "Workflow verification completed. All 5 workflows tested on 2026-04-24."
        })
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "saved" in text.lower():
            ok("save_session_note", text)
        else:
            fail("save_session_note", text[:80])
    except Exception as e:
        fail("save_session_note", str(e))

    # get_session_summary (should now include the note)
    try:
        result = await mcp.call_tool("get_session_summary", {})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "Workflow verification" in text or "Session Context" in text:
            ok("get_session_summary [with note]", "Note visible in summary ✓")
        else:
            warn("get_session_summary [with note]", text[:80])
    except Exception as e:
        fail("get_session_summary [with note]", str(e))

    # trim_context
    try:
        result = await mcp.call_tool("trim_context", {"keep_last": 5})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "trimmed" in text.lower() or "kept" in text.lower():
            ok("trim_context", text)
        else:
            fail("trim_context", text[:80])
    except Exception as e:
        fail("trim_context", str(e))

    # clear_session_context (full wipe test)
    try:
        result = await mcp.call_tool("clear_session_context", {})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "cleared" in text.lower():
            ok("clear_session_context", text)
        else:
            fail("clear_session_context", text[:80])
    except Exception as e:
        fail("clear_session_context", str(e))

    # Verify it's actually empty
    try:
        result = await mcp.call_tool("get_context_stats", {})
        text = result[0].text if hasattr(result[0], "text") else str(result)
        if "0" in text:
            ok("get_context_stats [after clear]", "Turn count = 0 ✓")
        else:
            warn("get_context_stats [after clear]", text[:80])
    except Exception as e:
        fail("get_context_stats [after clear]", str(e))


# ── Main Runner ───────────────────────────────────────────────────────────────
async def main():
    print(f"\n{BOLD}{'═'*55}{RESET}")
    print(f"{BOLD}  F.R.I.D.A.Y. — Full Workflow Verification Suite{RESET}")
    print(f"{BOLD}{'═'*55}{RESET}")

    # Use an isolated workspace so we don't pollute the main workspace
    import uuid, shutil
    test_workspace = repo_root / "workspace" / f"wf-verify-{uuid.uuid4().hex[:8]}"
    test_memory   = repo_root / "workspace" / f"wf-memory-{uuid.uuid4().hex[:8]}"
    test_workspace.mkdir(parents=True, exist_ok=True)
    test_memory.mkdir(parents=True, exist_ok=True)

    os.environ["FRIDAY_WORKSPACE_DIR"] = str(test_workspace)
    os.environ["FRIDAY_MEMORY_DIR"]    = str(test_memory)
    os.environ["MCP_SERVER_URL"]       = ""
    os.environ["FRIDAY_BROWSER_HEADLESS"] = "1"

    try:
        await workflow_1()
        await workflow_2()
        await workflow_3()
        await workflow_4()
        await workflow_5()
    finally:
        shutil.rmtree(test_workspace, ignore_errors=True)
        shutil.rmtree(test_memory,    ignore_errors=True)

    # ── Summary ────────────────────────────────────────────────────────────
    passed = sum(1 for r in results if r[0] == "PASS")
    warned = sum(1 for r in results if r[0] == "WARN")
    failed = sum(1 for r in results if r[0] == "FAIL")

    print(f"\n{BOLD}{'═'*55}")
    print(f"  Workflow Verification Summary")
    print(f"  {GREEN}{passed} passed{RESET}  {YELLOW}{warned} warnings{RESET}  {RED}{failed} failed{RESET}")
    print(f"{'═'*55}{RESET}\n")

    if failed:
        print(f"{RED}Failed checks:{RESET}")
        for status, label in results:
            if status == "FAIL":
                print(f"  • {label}")
    sys.exit(1 if failed else 0)


if __name__ == "__main__":
    asyncio.run(main())
